### ISSUE TITLE
Namespace testyomesh seems hardcoded

### ISSUE THREAD

**Issue by howardjohn** [Stono/testyomesh#1]
```
test/load-tester-5dccfd77df-vvsld[master]: {"timestamp":"2020-11-02T18:24:42.341Z","level":"info","module":"web-server","message":"running","method":"PATCH","searchParams":{"code":200,"servers":"testyomesh-1.testyomesh.svc.cluster.local/delayed"},"url":"http://testyomesh-3.testyomesh.svc.cluster.local/downstream"}
test/load-tester-5dccfd77df-vvsld[master]: {"timestamp":"2020-11-02T18:24:42.345Z","level":"error","module":"web-server","message":"PATCH: http://testyomesh-3.testyomesh.svc.cluster.local/downstream failed.","error":{"name":"RequestError","message":"getaddrinfo ENOTFOUND testyomesh-3.testyomesh.svc.cluster.local","stack":"at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:953:111)"}}
test/load-tester-5dccfd77df-vvsld[master]: {"timestamp":"2020-11-02T18:24:42.345Z","level":"info","module":"web-server","message":"running","method":"PUT","searchParams":{"code":200},"url":"http://testyomesh-3.testyomesh.svc.cluster.local/delayed"}
test/load-tester-5dccfd77df-vvsld[master]: {"timestamp":"2020-11-02T18:24:42.429Z","level":"error","module":"web-server","message":"HEAD: http://testyomesh-2.testyomesh.svc.cluster.local/instant failed.","error":{"name":"RequestError","message":"getaddrinfo ENOTFOUND testyomesh-2.testyomesh.svc.cluster.local","stack":"at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:953:111)"}}
test/load-tester-5dccfd77df-vvsld[master]: {"timestamp":"2020-11-02T18:24:42.429Z","level":"info","module":"web-server","message":"running","method":"HEAD","searchParams":{"code":202},"url":"http://testyomesh-1.testyomesh.svc.cluster.local/delayed"}
test/load-tester-5dccfd77df-vvsld[master]: {"timestamp":"2020-11-02T18:24:42.459Z","level":"error","module":"web-server","message":"PUT: http://testyomesh-1.testyomesh.svc.cluster.local/instant failed.","error":{"name":"RequestError","message":"getaddrinfo ENOTFOUND testyomesh-1.testyomesh.svc.cluster.local","stack":"at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:953:111)"}}
```

after `helm template . --namespace test | kubectl apply -f - -n test`

Works fine if I set namespace to `testyomesh`. Oddly I couldn't find where testyomesh actually comes from

**Comment by Stono** [comment]
Sorry, I should have documented, yes at the moment it is totally hardcoded to `testyomesh`!

It isn't in any of the manifests as the helm convention is to let that be controlled by the release namespace but the `operator` and `loadtester` code expects it, which I do intend to support other namespaces in the future.
