### ISSUE TITLE
Operator pod crashlookbackoff

### ISSUE THREAD

**Issue by ruigulala** [Stono/testyomesh#2]
For some reason, the operator pod isn't working properly on my side. I've installed testyomesh with the following.

```
helm template helmfile/charts/testyomesh/ | kubectl apply -n testyomesh -f -
```
 
```
{"timestamp":"2021-09-10T18:26:57.539Z","level":"info","module":"client","message":"using service account"}
{"timestamp":"2021-09-10T18:26:57.542Z","level":"info","module":"client","message":"loading kubernetes spec"}
{"timestamp":"2021-09-10T18:26:57.785Z","level":"info","module":"client","message":"loading complete"}
{"timestamp":"2021-09-10T18:26:57.789Z","level":"info","module":"config","message":"config loaded"}
{"timestamp":"2021-09-10T18:26:57.791Z","level":"info","module":"AuthPolicyToggle","message":"next run in 179824ms"}
{"timestamp":"2021-09-10T18:26:57.791Z","level":"info","module":"RestartSimpleService","message":"next run in 272031ms"}
{"timestamp":"2021-09-10T18:26:57.791Z","level":"info","module":"web-server","message":"starting web server on port 8080"}
{"timestamp":"2021-09-10T18:26:57.793Z","level":"info","module":"web-server","message":"web server started"}
{"timestamp":"2021-09-10T18:29:57.731Z","level":"error","module":"client","message":"Error getting item from kubernetes","error":{"name":"Error","message":"authorizationpolicies.security.istio.io \"toggle\" is forbidden: User \"system:serviceaccount:testyomesh:operator\" cannot get resource \"authorizationpolicies\" in API group \"security.istio.io\" in the namespace \"testyomesh\"","stack":"at /app/lib/kubernetes/monkeypatch/client.js:198:35"}}
{"timestamp":"2021-09-10T18:29:57.732Z","level":"error","module":"AuthPolicyToggle","message":"failed to run","error":{"name":"Error","message":"Error: authorizationpolicies.security.istio.io \"toggle\" is forbidden: User \"system:serviceaccount:testyomesh:operator\" cannot get resource \"authorizationpolicies\" in API group \"security.istio.io\" in the namespace \"testyomesh\"","stack":"at Kubernetes.<anonymous> (/app/lib/kubernetes/client.js:245:27)"}}
{"timestamp":"2021-09-10T18:29:57.732Z","level":"info","module":"AuthPolicyToggle","message":"next run in 454161ms"}
{"timestamp":"2021-09-10T18:31:29.893Z","level":"info","module":"RestartSimpleService","message":"patching testyomesh-1 to trigger a deployment"}
{"timestamp":"2021-09-10T18:31:29.895Z","level":"info","module":"RestartSimpleService","message":"next run in 250668ms"}
{"timestamp":"2021-09-10T18:31:29.916Z","level":"error","module":"client","message":"Error getting item from kubernetes","error":{"name":"Error","message":"deployments.apps \"testyomesh-1\" is forbidden: User \"system:serviceaccount:testyomesh:operator\" cannot get resource \"deployments\" in API group \"apps\" in the namespace \"testyomesh\"","stack":"at /app/lib/kubernetes/monkeypatch/client.js:198:35"}}
Unhandled Rejection! Error: Error: deployments.apps "testyomesh-1" is forbidden: User "system:serviceaccount:testyomesh:operator" cannot get resource "deployments" in API group "apps" in the namespace "testyomesh"
    at Kubernetes.<anonymous> (/app/lib/kubernetes/client.js:245:27)
    at Generator.throw (<anonymous>)
    at rejected (/app/lib/kubernetes/client.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I'm using the following kubernetes version.

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.9-gke.701", GitCommit:"5f13de0910e4eb40c1c6b3b44704b25313a2c80c", GitTreeState:"clean", BuildDate:"2021-08-18T17:05:42Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

The role looks fine tho.

```
$ k get role -n testyomesh -oyaml
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app":"testyomesh","component":"operator"},"name":"operator","namespace":"testyomesh"},"rules":[{"apiGroups":["apps"],"resources":["deployments"],"verbs":["list","get","patch"]},{"apiGroups":["security.istio.io"],"resources":["authorizationpolicies"],"verbs":["list","get","create","delete"]}]}
    creationTimestamp: "2021-09-09T21:19:52Z"
    labels:
      app: testyomesh
      component: operator
    name: operator
    namespace: testyomesh
    resourceVersion: "5262812"
    uid: 77cd7bc7-e727-49df-b085-4245e758ceac
  rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - list
    - get
    - patch
  - apiGroups:
    - security.istio.io
    resources:
    - authorizationpolicies
    verbs:
    - list
    - get
    - create
    - delete
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by ruigulala** [comment]
Ok. It's because I didn't set `namespace: {{ .Release.Namespace }}` in the `helm template` command. So the rolebinding is trying to bind the SA in default namespace which doesn't exist.
